eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
server:
  port: 8092
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-spider:
      path: /spider/**
      serviceId: service-feign
    api-b:
      path: /user/**
      serviceId: service-feign