server:
  port: 8082

spring:
  datasource:
      name: xss
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/xss
      username: root
      password:
      type: com.alibaba.druid.pool.DruidDataSource


mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.larryluk.xss.dao