server:
  port: 8083

spring:
  application:
    name: service-spider

constant:
    search:
        url: http://www.biquge.com.tw/modules/article/soshu.php?searchkey=
    base: http://www.biquge.com.tw

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/