server:
  port: 8083

spring:
  datasource:
      name: xss
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/xss
      username: root
      password:
      type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: service-spider

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.larryluk.xss.dao


constant:
    search:
        url: http://www.biquge.com.tw/modules/article/soshu.php?searchkey=
    base: http://www.biquge.com.tw

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/